---
dist: bionic

language: python

python:
- "3.6"
- "3.7"
- "3.8"

env:
- ENGINE=docker
- ENGINE=docker WITH_K8S=1
- ENGINE=singularity
- ENGINE=podman

services: docker

before_install:
- src/scripts/install_singularity.sh
- src/scripts/install_podman.sh
- src/scripts/install_k8s.sh
- pip install coverage

install:
- pip install src/[dev]
- black --check --diff .

script:
# run tests
- coverage run -m unittest src/test/test_*
# generate versioning file (src/popper/_version.py)
- popper version
# run docker image pipeline
- popper run --allow-undefined-secrets-in-ci

after_success:
- bash <(curl -s https://codecov.io/bash)
